### ISSUE TITLE
chain multiple scripts together

### ISSUE THREAD

**Issue by jkone27** [CaptnCodr/Fli#66]
would be nice to have a way to chain multiple scripts together and specify the chain strategy (sequential or parallel background fork and rejoin --> first error exit?)

```
cli {

}
>=> 
cli {

}
>=> 
cli {

}
>=> 
cli {

}
|> Command.Execute (for normal chaining with '&&')

or

|> Command.ExecuteParallel // parallel strategies...below
```

here for ref

<img width="749" alt="image" src="https://github.com/CaptnCodr/Fli/assets/10419217/8ee1a124-265d-4d26-a712-de2a4aec77cb">

https://stackoverflow.com/questions/3004811/how-do-you-run-multiple-programs-in-parallel-from-a-bash-script

**Comment by CaptnCodr** [comment]
Hey @jkone27 
I have a build script here: https://github.com/CaptnCodr/Fli/blob/main/build.fsx
and there is `Output.throwIfErrored`, it will stop when the `exitCode` is not 0. 
There is `Output.throw (func: Output -> bool) (output: Output)`, where you can define when the execution should stop.

Parallelism isn't planned so far, it's because those actions are mostly run from the script and are sequential.
For those kind of parallelism, there is `Command.executeAsync`.

**Comment by jkone27** [comment]
ah nice thanks!
